services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest #imagem para rpi
    pull_policy: always
    restart: unless-stopped
    tty: true
    ports:
      - 11434:11434
    volumes:
    #  - /home/pi/ollama/data:/root/.ollama
      - ollama:/root/.ollama  

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
      - 'WEBUI_SECRET_KEY=elvis123456'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}